info: dev3
spring:
  rabbitmq:
      host: 192.168.43.245
      port: 5672
      username: guest
      password: guest
  cloud:
    stream:
      default-binder: defaultRabbit
      binders: 
        myMessage2:
          destination: myMessage2 
