spring:
  datasource:
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///self
  redis:
    host: 192.168.0.115
    password: 123456
    port: 6379
